apiVersion: v1
kind: Service
metadata:
  name: be-prod
  namespace: prod
spec:
  selector:
    app: be-prod
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-prod
  namespace: prod
spec:
  selector:
    matchLabels:
      app: be-prod
  template:
    metadata:
      labels:
        app: be-prod
    spec:
      containers:
      - name: be-prod
        image: varrence/prod-be:PLACEHOLDER
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: secret-prod-be
                key: DATABASE_USERNAME
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-prod-be
                key: DATABASE_PASSWORD
          - name: DATABASE_DATABASE
            valueFrom:
              secretKeyRef:
                name: secret-prod-be
                key: DATABASE_DATABASE
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: secret-prod-be
                key: DATABASE_HOST
          - name: DATABASE_PORT
            valueFrom:
              secretKeyRef:
                name: secret-prod-be
                key: DATABASE_PORT
        volumeMounts:
          - mountPath: /app/.env
            name: configmap-prod-be
            subPath: .env
      volumes:
        - name: configmap-prod-be
          configMap:
            name: configmap-prod-be
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-be-prod
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "server: hide";
      more_set_headers "X-Powered-By: cilsy";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: SAMEORIGIN";
      more_set_headers "X-Xss-Protection: 1; mode=block";
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
#    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:389364182454:certificate/b9d1f89d-b3e6-48c4-9741-4c7a6754a48e
#    nginx.ingress.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:389364182454:certificate/b9d1f89d-b3e6-48c4-9741-4c7a6754a48e
spec:
  ingressClassName: nginx
  rules:
  - host: be-prod.cilsy.my.id
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: be-prod
            port:
              number: 5000
  tls:
    - hosts:
        - be-prod.cilsy.my.id
      secretName: wildcard-varrence
